services:
  - type: web
    name: cytopath-ai
    env: python
    buildCommand: pip install -r requirements.txt
    startCommand: gunicorn web_app.main:app --bind 0.0.0.0:$PORT --workers 4 --worker-class uvicorn.workers.UvicornWorker --timeout 120
    envVars:
      - key: PYTHON_VERSION
        value: 3.11.0
      - key: PORT
        value: 8000
      - key: PYTHONPATH
        value: .
    healthCheckPath: /health 