services:
  - type: web
    name: cytopath-ai
    env: python
    region: frankfurt
    buildCommand: pip install -r requirements.txt
    startCommand: gunicorn --chdir web_app main:app --workers 4 --worker-class uvicorn.workers.UvicornWorker --bind 0.0.0.0:$PORT --timeout 120 --log-level debug
    envVars:
      - key: PYTHON_VERSION
        value: 3.11.0
      - key: PORT
        value: 8000
      - key: ENVIRONMENT
        value: production
      - key: PYTHONPATH
        value: /opt/render/project/src
    healthCheckPath: /health
    autoDeploy: false
    plan: starter
    scaling:
      minInstances: 1
      maxInstances: 1
    buildFilter:
      paths:
        - requirements.txt
        - web_app/**
        - src/** 