data:
  train_dir: "data/train"
  val_dir: "data/val"
  test_dir: "data/test"
  image_size: [224, 224]

training:
  model_dir: "models"
  batch_size: 32
  num_epochs: 100
  learning_rate: 0.001
  weight_decay: 0.01
  num_workers: 4
  patience: 10  # Early stopping patience
  
  # Data augmentation
  augmentation:
    random_horizontal_flip: 0.5
    random_vertical_flip: 0.5
    random_rotation: 20
    color_jitter:
      brightness: 0.2
      contrast: 0.2
      saturation: 0.2
      hue: 0.1

model:
  architecture: "efficientnet_b0"
  pretrained: true
  num_classes: 5
  dropout_rates: [0.3, 0.2, 0.1]
  feature_dims: [512, 256]

logging:
  wandb_project: "cervical-lesion-detection"
  log_interval: 10  # Log every N batches
  save_interval: 5  # Save checkpoint every N epochs
